package redhat.example.quickstart;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.kie.api.definition.type.Label(value = "purchase ordr")
public class PurchaseOrder  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String address;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String city;
    
    @org.kie.api.definition.type.Label(value = "description")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String description;
    
    @org.kie.api.definition.type.Label(value = "item id")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer itemId;
    
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.String name;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.math.BigDecimal price;
    
    @org.kie.api.definition.type.Label(value = "quantity")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer quantity;
    
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.String state;
    
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.String zip;

    public PurchaseOrder() {
    }

    public PurchaseOrder(java.lang.Integer itemId, java.lang.Integer quantity, java.lang.String description, java.math.BigDecimal price, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String zip, java.lang.String name) {
        this.itemId = itemId;
        this.quantity = quantity;
        this.description = description;
        this.price = price;
        this.address = address;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.name = name;
    }


    
    public java.lang.String getAddress() {
        return this.address;
    }

    public void setAddress(  java.lang.String address ) {
        this.address = address;
    }
    
    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(  java.lang.String city ) {
        this.city = city;
    }
    
    public java.lang.String getDescription() {
        return this.description;
    }

    public void setDescription(  java.lang.String description ) {
        this.description = description;
    }
    
    public java.lang.Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(  java.lang.Integer itemId ) {
        this.itemId = itemId;
    }
    
    public java.lang.String getName() {
        return this.name;
    }

    public void setName(  java.lang.String name ) {
        this.name = name;
    }
    
    public java.math.BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(  java.math.BigDecimal price ) {
        this.price = price;
    }
    
    public java.lang.Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(  java.lang.Integer quantity ) {
        this.quantity = quantity;
    }
    
    public java.lang.String getState() {
        return this.state;
    }

    public void setState(  java.lang.String state ) {
        this.state = state;
    }
    
    public java.lang.String getZip() {
        return this.zip;
    }

    public void setZip(  java.lang.String zip ) {
        this.zip = zip;
    }
}